site_name: ${{values.name | dump}}
site_description: ${{values.description | dump}}

nav:
  - Introduction: index.md
  - API Documentation: api.md
  - Development: development.md
  - Artifactory Integration: artifactory-integration.md

plugins:
  - techdocs-core