---
# yamllint disable rule:line-length
apiVersion: app.appvia.io/v2beta1
kind: AppEnv
metadata:
  name: ${{ values.name }}-staging
  namespace: ws-${{ values.workspaceKey }}
spec:
  application: ${{ values.name }}
  cloud: aws
  cloudAccessConfigRef:
    name: aws-nonprod
    workspace: ${{ values.workspaceKey }}
  clusterRef:
    group: compute.appvia.io
    kind: Cluster
    name: ${{ values.nonProdCluster }}
    namespace: ws-${{ values.workspaceKey }}
    version: v2beta2
  name: staging
  namespace: ${{ values.name }}-staging
  region: eu-west-2
  stage: nonprod
