---
# yamllint disable rule:line-length
apiVersion: app.appvia.io/v2beta1
kind: AppEnv
metadata:
  name: ${{ values.name }}-prod
  namespace: ws-${{ values.workspaceKey }}
spec:
  application: ${{ values.name }}
  cloud: ${{ values.cloud }}
  cloudAccessConfigRef:
    name: ${{ values.cloud }}-prod
    workspace: ${{ values.workspaceKey }}
  clusterRef:
    group: compute.appvia.io
    kind: Cluster
    name: ${{ values.prodCluster }}
    namespace: ws-${{ values.workspaceKey }}
    version: v2beta2
  name: prod
  namespace: ${{ values.name }}-prod
  stage: prod
