---
# yamllint disable rule:line-length
apiVersion: app.appvia.io/v2beta1
kind: AppEnv
metadata:
  name: ${{ values.name }}-prod
  namespace: ws-${{ values.workspaceKey }}
spec:
  application: ${{ values.name }}
  cloud: azure
  cloudAccessConfigRef:
    name: azure-prod
    workspace: ${{ values.workspaceKey }}
  clusterRef:
    group: compute.appvia.io
    kind: Cluster
    name: ${{ values.cluster }}
    namespace: ws-${{ values.workspaceKey }}
    version: v2beta2
  key: prod
  name: prod
  namespace: ${{ values.workspaceKey }}-${{ values.name }}-prod
  region: eu-west-2
  stage: prod
