{% raw %}
name: teardown-preview

on:
  pull_request:
    types: [closed]

permissions:
  contents: read

env:
  WAYFINDER_SERVER: ${{ vars.WAYFINDER_SERVER }}
  WAYFINDER_TOKEN: ${{ secrets.WAYFINDER_TOKEN_NONPROD }}
  WAYFINDER_WORKSPACE: ${{ vars.WAYFINDER_WORKSPACE }}


jobs:
  wf:
    name: "Wayfinder toolbox"
    runs-on: ubuntu-latest
    container: quay.io/appvia-wf-dev/wftoolbox:latest
    outputs:
      version: ${{ steps.wayfinder.outputs.version }}
      toolbox: ${{ steps.wayfinder.outputs.toolbox }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set Wayfinder toolbox version
        id: wayfinder
        # To use this syntax, we must have the repository checked out
        uses: ./.github/actions/wayfinder-toolbox-version

  teardown-preview:
    runs-on: ubuntu-latest
    needs: 
      - wf
    container:
      image: ${{ needs.wf.outputs.toolbox }}
    steps:
      - name: Clean up old resources
        run: |
          export PREVIEW_ENV="${{ vars.APPLICATION_NAME }}-pr-${{ github.event.pull_request.number }}"
          wf delete appenv ${PREVIEW_ENV}

{% endraw %}
