{% raw %}
name: teardown-preview

on:
  pull_request:
    types: [closed]

permissions:
  contents: read

jobs:
  teardown-preview:
    runs-on: ubuntu-latest
    container:
      image: quay.io/${{ vars.WAYFINDER_QUAY_ORG }}/wftoolbox:${{ vars.WAYFINDER_VERSION }}
    steps:
      - name: Clean up old resources
        env:
          WAYFINDER_SERVER: ${{ vars.WAYFINDER_SERVER }}
          WAYFINDER_WORKSPACE: ${{ vars.WAYFINDER_WORKSPACE }}
          WAYFINDER_TOKEN: ${{ secrets.WAYFINDER_TOKEN_NONPROD }}
        run: |
          {% endraw %}
          export APP_NAME="${{ values.name }}"
          {% raw %}
          export PREVIEW_ENV="${APP_NAME}-pr-${{ github.event.pull_request.number }}"
          wf delete appenv ${PREVIEW_ENV}
{% endraw %}
