{% raw %}
name: Wayfinder deploy to staging

on:
  push:
    branches:
    - main
  workflow_dispatch:

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  wf:
    name: "Wayfinder version and toolbox image"
    runs-on: ubuntu-latest
    container: quay.io/appvia-wf-dev/wftoolbox:latest
    outputs:
      version: ${{ steps.version.outputs.WAYFINDER_VERSION }}
      toolbox: ${{ steps.toolbox.outputs.WAYFINDER_TOOLBOX_IMAGE }}
    steps:
    - name: Current Wayfinder version
      id: version
      env:
        WAYFINDER_SERVER: ${{ vars.WAYFINDER_SERVER }}
        WAYFINDER_TOKEN: ${{ secrets.WAYFINDER_TOKEN }}
      run: echo "WAYFINDER_VERSION=$(wf serverinfo -o yaml | grep release | awk '{print $2}')" >> $GITHUB_OUTPUT
    - name: Wayfinder toolbox image
      id: toolbox
      run: |
        if [[ "${{ steps.version.outputs.WAYFINDER_VERSION }}" = *-* ]]; then
          echo "WAYFINDER_TOOLBOX_IMAGE=quay.io/appvia-wf-dev/wftoolbox:${{ steps.version.outputs.WAYFINDER_VERSION }}" >> $GITHUB_OUTPUT
        else
          echo "WAYFINDER_TOOLBOX_IMAGE=quay.io/appvia-wayfinder/wftoolbox:${{ steps.version.outputs.WAYFINDER_VERSION }}" >> $GITHUB_OUTPUT
        fi

  wf-diff:
    name: "Wayfinder Diff"
    runs-on: ubuntu-latest
    needs: 
      - wf
    container: ${{ needs.wf.outputs.toolbox }}
    outputs:
      result: ${{ steps.diff.outcome }}
      stdout: ${{ steps.diff.outputs.stdout }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Wayfinder diff
        id: diff
        shell: bash
        env:
          WAYFINDER_SERVER: ${{ vars.WAYFINDER_SERVER }}
          WAYFINDER_TOKEN: ${{ secrets.WAYFINDER_TOKEN_NONPROD }}
          WAYFINDER_WORKSPACE: ${{ vars.WAYFINDER_WORKSPACE }}
        run: |
          set +e
          wf diff -f ./wayfinder --owner ${{ vars.WAYFINDER_RESOURCE_OWNER }} --prune --prune-scope all 2>&1 | tee stdout.txt
          diffExitCode=$?
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "stdout<<$EOF" >> "$GITHUB_OUTPUT"
          cat stdout.txt >> "$GITHUB_OUTPUT"
          echo "$EOF" >> "$GITHUB_OUTPUT"
          exit $diffExitCode
  wf-apply:
    name: "Wayfinder Apply"
    needs:
      - wf
      - wf-diff
    runs-on: ubuntu-latest
    container: ${{ needs.wf.outputs.toolbox }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Wayfinder
        env:
          WAYFINDER_SERVER: ${{ vars.WAYFINDER_SERVER }}
          WAYFINDER_TOKEN: ${{ secrets.WAYFINDER_TOKEN_NONPROD }}
          WAYFINDER_WORKSPACE: ${{ vars.WAYFINDER_WORKSPACE }}
          APP_IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        run: |
          wf apply -f ./wayfinder --owner ${{ vars.WAYFINDER_RESOURCE_OWNER }} --prune --prune-scope all --wait-for-ready 5m --confirm
          tag=sha-$(echo ${{ github.sha }} | cut -c 1-7)
          {% endraw %}
          wf deploy app ${{ values.name }} nonprod --component-container-image app=app=${APP_IMAGE}:${tag}
