{% raw %}
name: Wayfinder deploy to prod

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Image tag to deploy to production'
        required: true
        default: 'main'

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  WAYFINDER_SERVER: ${{ vars.WAYFINDER_SERVER }}
  WAYFINDER_TOKEN: ${{ secrets.WAYFINDER_TOKEN }}
  WAYFINDER_WORKSPACE: ${{ vars.WAYFINDER_WORKSPACE }}
  WAYFINDER_RESOURCE_OWNER: ${{ vars.WAYFINDER_RESOURCE_OWNER }}

jobs:
  wf:
    name: "Wayfinder toolbox"
    runs-on: ubuntu-latest
    container: quay.io/appvia-wf-dev/wftoolbox:latest
    outputs:
      version: ${{ steps.wayfinder.outputs.version }}
      toolbox: ${{ steps.wayfinder.outputs.toolbox }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set Wayfinder toolbox version
        id: wayfinder
        # To use this syntax, we must have the repository checked out
        uses: ./.github/actions/wayfinder-toolbox-version

  wf-diff:
    name: "Wayfinder Diff"
    runs-on: ubuntu-latest
    needs:
      - wf
    container: ${{ needs.wf.outputs.toolbox }}
    outputs:
      result: ${{ steps.diff.outputs.result }}
      stdout: ${{ steps.diff.outputs.stdout }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Wayfinder diff
        id: diff
        uses: ./.github/actions/wayfinder-diff

  wf-apply:
    name: "Wayfinder Apply"
    needs:
      - wf
      - wf-diff
    runs-on: ubuntu-latest
    container: ${{ needs.wf.outputs.toolbox }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Wayfinder apply
        id: apply
        uses: ./.github/actions/wayfinder-apply
        env:
          APP_NAME: ${{ vars.APPLICATION_NAME }}
          APP_IMAGE_TAG: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.image-tag }}
          APP_STAGE: prod

{% endraw %}
